# Generated by Django 5.2.3 on 2025-06-16 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_booking_travelers'),
    ]

    operations = [
        migrations.AddField(
            model_name='Booking',
            name='tour_date',
            field=models.DateField(default='2025-06-16'),
            preserve_default=False,
        ),
    ]
